### ISSUE TITLE
upgrade for rspec 3

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/rspec-solr#4]

**Comment by tampakis** [comment]
I forked this gem and upgraded to rspec3. Outside some of the spacing of hashes in the spec error messages which changed on the upgrade to rspec3 [in this commit](https://github.com/rspec/rspec-expectations/commit/aae135783a860ccccd4257880e8b6b71ea02d8cb), everything else behaves the same way. 

Are you interested in taking a pull request? We only have a few relevancy tests so far (which work the same way in rspec2 and rspec3), so I'm curious to see if this commit is compatible with the Stanford relevancy tests. https://github.com/pulibrary/rspec-solr/tree/rspec3 
To try it out just change your Gemfile as follows:
```
gem "rspec-solr", :git => "https://github.com/pulibrary/rspec-solr.git", :branch => "rspec3"
gem "rspec", "~> 3.2"
```

You can also avoid deprecations for the 'should' syntax if you explicitly allow it in your `spec_helper.rb` config:
```
RSpec.configure do |config|
  config.expect_with :rspec do |c|
    c.syntax = [:should, :expect]
  end
end
```

**Comment by cbeer** [comment]
Yes, please send a pull request.

**Comment by ndushay** [comment]
Thank you for this!  A pull request would be best.
